name: Bug Report
description: File a bug report to help us improve batless
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With file '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: command-used
    attributes:
      label: Command used
      description: The exact batless command that caused the issue
      placeholder: "batless src/main.rs --mode=highlight --max-lines=10"
    validations:
      required: true

  - type: textarea
    id: file-content
    attributes:
      label: Sample file content (if relevant)
      description: If the issue is related to a specific file, please provide a minimal example
      render: text
    validations:
      required: false

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: batless-version
    attributes:
      label: batless version
      description: What version of batless are you running? (run `batless --version`)
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: installation-method
    attributes:
      label: Installation method
      description: How did you install batless?
      placeholder: "cargo install batless, built from source, downloaded binary, etc."
    validations:
      required: true

  - type: textarea
    id: terminal-info
    attributes:
      label: Terminal information
      description: What terminal are you using? Any relevant environment details?
      placeholder: "Terminal: iTerm2, Shell: zsh, TERM=xterm-256color"
    validations:
      required: false

  - type: textarea
    id: error-output
    attributes:
      label: Error output
      description: Any error messages or unexpected output
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I am using the latest version of batless
          required: false
