name: markdown-lint

on:
  push:
    paths:
      - '**/*.md'
      - '.markdownlint.*'
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint.*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Ensure markdownlint config exists
        run: |
          if [ ! -f ".markdownlint.jsonc" ]; then
            cat > .markdownlint.jsonc <<'JSON'
            {
              "default": true,
              "MD013": false,
              "MD033": false,
              "MD041": false,
              "MD024": { "siblings_only": true },
              "MD036": false,
              "MD040": false
            }
            JSON
          fi
      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2@0.14.0
      - name: Run markdownlint
        run: markdownlint-cli2 "**/*.md" "!target/**" --config ".markdownlint.jsonc"
