name: markdown-lint

on:
  push:
    paths:
      - '**/*.md'
      - '.markdownlint.*'
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint.*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '20'
      - name: Ensure markdownlint config exists
        run: |
          if [ ! -f ".markdownlint.jsonc" ]; then
            cat > .markdownlint.jsonc <<'JSON'
            {
              "default": true,
              "MD013": false,
              "MD033": false,
              "MD041": false,
              "MD024": { "siblings_only": true },
              "MD036": false,
              "MD040": false
            }
            JSON
          fi
          if [ ! -f "markdownlint-cli2.jsonc" ]; then
            cat > markdownlint-cli2.jsonc <<'JSON'
            {
              "globs": ["**/*.md", "!target/**"],
              "config": {
                "default": true,
                "MD013": false,
                "MD033": false,
                "MD041": false,
                "MD024": { "siblings_only": true },
                "MD036": false,
                "MD040": false
              }
            }
            JSON
          fi
      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2@0.14.0
      - name: Run markdownlint
        continue-on-error: true
        run: markdownlint-cli2 --config "markdownlint-cli2.jsonc"
