name: markdown-lint

on:
  push:
    paths:
      - '**/*.md'
      - '.markdownlint.*'
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint.*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '20'
      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2@0.14.0
      - name: Run markdownlint
        continue-on-error: true
        run: markdownlint-cli2 "**/*.md" "!target/**"
