name: markdown-lint

on:
  push:
    paths:
      - '**/*.md'
      - '.markdownlint.*'
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint.*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2@0.14.0
      - name: Run markdownlint
        run: markdownlint-cli2 "**/*.md" "!target/**"
