name: Manual Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      workflow_type:
        description: 'Type of workflow to run'
        required: true
        type: choice
        options:
          - 'full-test-suite'
          - 'security-audit'
          - 'performance-benchmark'
          - 'quality-check'
          - 'quick-validation'
      skip_tests:
        description: 'Skip time-consuming tests'
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  checks: write
  security-events: write

jobs:
  dispatch:
    runs-on: ubuntu-latest
    outputs:
      should_run_tests: ${{ steps.decision.outputs.run_tests }}
      should_run_security: ${{ steps.decision.outputs.run_security }}
      should_run_benchmarks: ${{ steps.decision.outputs.run_benchmarks }}
      should_run_quality: ${{ steps.decision.outputs.run_quality }}
    steps:
      - name: Make workflow decisions
        id: decision
        run: |
          case "${{ github.event.inputs.workflow_type }}" in
            "full-test-suite")
              echo "run_tests=true" >> $GITHUB_OUTPUT
              echo "run_security=true" >> $GITHUB_OUTPUT
              echo "run_benchmarks=true" >> $GITHUB_OUTPUT
              echo "run_quality=true" >> $GITHUB_OUTPUT
              ;;
            "security-audit")
              echo "run_tests=false" >> $GITHUB_OUTPUT
              echo "run_security=true" >> $GITHUB_OUTPUT
              echo "run_benchmarks=false" >> $GITHUB_OUTPUT
              echo "run_quality=false" >> $GITHUB_OUTPUT
              ;;
            "performance-benchmark")
              echo "run_tests=false" >> $GITHUB_OUTPUT
              echo "run_security=false" >> $GITHUB_OUTPUT
              echo "run_benchmarks=true" >> $GITHUB_OUTPUT
              echo "run_quality=false" >> $GITHUB_OUTPUT
              ;;
            "quality-check")
              echo "run_tests=false" >> $GITHUB_OUTPUT
              echo "run_security=false" >> $GITHUB_OUTPUT
              echo "run_benchmarks=false" >> $GITHUB_OUTPUT
              echo "run_quality=true" >> $GITHUB_OUTPUT
              ;;
            "quick-validation")
              echo "run_tests=true" >> $GITHUB_OUTPUT
              echo "run_security=false" >> $GITHUB_OUTPUT
              echo "run_benchmarks=false" >> $GITHUB_OUTPUT
              echo "run_quality=false" >> $GITHUB_OUTPUT
              ;;
          esac

  quick-validation:
    if: needs.dispatch.outputs.should_run_tests == 'true'
    needs: dispatch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@be73d8f40701655e1646db5b78c130f838f86ffc # stable
      - name: Run quick tests
        run: |
          cargo test --lib
          cargo clippy -- -D warnings
          cargo fmt --check
      
  security-audit:
    if: needs.dispatch.outputs.should_run_security == 'true'
    needs: dispatch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@be73d8f40701655e1646db5b78c130f838f86ffc # stable
      - name: Install cargo-audit
        run: cargo install cargo-audit --locked
      - name: Run security audit
        run: cargo audit

  quality-check:
    if: needs.dispatch.outputs.should_run_quality == 'true'
    needs: dispatch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@be73d8f40701655e1646db5b78c130f838f86ffc # stable
      - name: Run quality checks
        run: |
          cargo clippy --all-targets --all-features -- -D warnings
          cargo fmt --all -- --check

  performance-benchmark:
    if: needs.dispatch.outputs.should_run_benchmarks == 'true'
    needs: dispatch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@be73d8f40701655e1646db5b78c130f838f86ffc # stable
      - name: Build release binary
        run: cargo build --release
      - name: Basic performance test
        run: |
          echo "Testing basic performance..."
          time ./target/release/batless README.md --max-lines=10

  summary:
    runs-on: ubuntu-latest
    needs: [dispatch, quick-validation, security-audit, quality-check, performance-benchmark]
    if: always()
    steps:
      - name: Workflow summary
        run: |
          echo "# Manual Workflow Execution Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Workflow Type:** ${{ github.event.inputs.workflow_type }}" >> $GITHUB_STEP_SUMMARY
          echo "**Skip Tests:** ${{ github.event.inputs.skip_tests }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Job Results" >> $GITHUB_STEP_SUMMARY
          echo "- Validation: ${{ needs.quick-validation.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Security: ${{ needs.security-audit.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Quality: ${{ needs.quality-check.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Performance: ${{ needs.performance-benchmark.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY